# These are requirements that have been known to be problamatic, this
# could be for a number of reasons:
# * Excessive backtracking causing slow resolution
# * Excessive backtracking causing build failure
# * Excessive backtracking causing ResolutionTooDeep
#
# Scenarios may be taken from other installers as even if pip doesn't
# currently file the resolution problematic it might one day regress

[autogluon]
# https://github.com/pypa/pip/issues/12990
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["autogluon==1.1.1"]

[pip-issue-12754]
# https://github.com/pypa/pip/issues/12754
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-06-07T14:00:00"
requirements = [
    "auditree-arboretum>=0.5.0",
    "deprecated>=1.2.10",
    "configparser",
    "python-dateutil",
    "PyYAML",
    "requests",
    "ilcli>=0.3.2",
    "PyJWT>=2.6.0",
    "python-dateutil",
    "requests>=2.28.2",
    "configparser",
    "python-dateutil",
    "PyYAML",
    "requests",
    "python-dateutil<3.0.0",
    "SoftLayer>=5.7.2",
    "sdcclient>=0.10.0",
    "pygithub>=1.58.0",
    "kubernetes>=21.7.0",
    "pytenable>=1.4.12",
    "strenum>=0.4.10 ",
    "ibm-platform-services>=0.30.3 ",
    "ibm_cloud_sdk_core>=3.16.1",
    "GitPython",
    "ibm-cos-sdk >=2.12.1",
    "ibm-platform-services >=0.22.5",
]

[TTS]
# https://github.com/pypa/pip/issues/12305
python_version = "3.8"
platform_system = "Linux"
datetime = "2023-10-01T14:00:00"
requirements = ["TTS"]

[boto3-urllib3-transient]
# https://github.com/astral-sh/uv/issues/1398
python_version = "3.9"
platform_system = "Linux"
datetime = "2023-10-01T14:00:00"
requirements = [
    "click >= 7.0",
    "click-loglevel ~= 0.2",
    "dandi >= 0.24.0",
    "psutil ~= 5.9",
    "pyyaml",
    "selenium",
]

[numpy-numba]
# https://github.com/astral-sh/uv/issues/6281#issuecomment-2316240724
python_version = "3.10"
platform_system = "Linux"
datetime = "2024-08-28T14:00:00"
requirements = [
    "numpy>=2.1,<2.2",
    "numba<=0.60,>0.1"
]

[starlette-fastapi]
# https://github.com/astral-sh/uv/issues/1575
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-02-17T14:00:00"
requirements = [
    "starlette<=0.36.0",
    "fastapi<=0.115.2",
]

[sentry-rapid-json]
# https://github.com/astral-sh/uv/issues/8157
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-10T14:00:00"
requirements = [
    "python-rapidjson<=1.20,>=1.4",
    "sentry-kafka-schemas<=0.1.113,>=0.1.50",
]

[apache-airflow-beam]
# https://github.com/astral-sh/uv/issues/3078#issuecomment-2062907457
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-04-17T14:00:00"
requirements = [
    "apache-airflow[apache-beam]==2.8.4",
]

[airflow-beam-dill]
# https://github.com/astral-sh/uv/issues/3078#issuecomment-2062907457
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-04-17T14:00:00"
requirements = [
    "dill>=0.2.2",
    "apache-beam<=2.49.0",
]

[kedro-test]
# https://github.com/pradyunsg/pip-resolver-benchmarks/discussions/8#discussioncomment-7807758
python_version = "3.10"
platform_system = "Linux"
datetime = "2023-12-09T14:00:00"
requirements = [
    "kedro[test]==0.18.13",
]

[sphinx]
# https://github.com/pypa/pip/issues/12430
python_version = "3.11"
platform_system = "Linux"
datetime = "2023-12-09T14:00:00"
requirements = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-toolbox",
    "myst-parser",
    "sphinxcontrib-bibtex",
    "nbsphinx",
]

[backtracks-to-old-scipy]
# https://github.com/pypa/pip/issues/13037
python_version = "3.10"
platform_system = "Linux"
datetime = "2024-10-22T14:00:00"
requirements = [
    "numpy==1.21.5",
    "spacy<4.0.0,>=3.0.0",
    "mlflow<3.0.0,>=2.13.0",
]
